# Candace Savonen Mar 2022

name: Testing ottr-reports
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Run Reports
      id: run-reports
      uses: ./
      with:
        token: ${{ secrets.GH_PAT }}
        check_spelling: true
        spelling_error_min: 0
        check_urls: true
        url_error_min: 0
        check_quiz_form: true
        quiz_error_min: 0
        branch_name: ${GITHUB_HEAD_REF}
        sort_dictionary: true
